# shared/reusable types.
# To use a shared type it must be referencd `as: <name>`
#  so with the example type it would be `as: severity`
types:
  - name: severity
    type: enum
    variants:
      - name: DBG
        display:
          fg: orange
          bold: true

# type of events and scheme of their rendering
events:
  - name: ReqLog
    matcher:
      event: RequestLog
    scheme:
      - name: asdf
        optional: true
        postfix:
          literal: " "
          display:
            bg: red
      - name: ts
        display:
          fg: white
      - name: status
        display:
          fg: green
        prefix: " "
      - name: method
        prefix: " "
      - name: path
        prefix: " "
      - name: took
        display:
          bold: true
        prefix: " "
      # - name: ts
      #   type: datetime
      # - special: rest
  - name: ServerShutdown
    matcher:
      event: ServerShutdown
    scheme:
      - name: ts
        display:
          fg: white
      - name: msg
        display:
          fg: white
        prefix: " "
  - name: ServerStop
    matcher:
      event: ServerStop
    scheme:
      - name: ts
        postfix: " "
        display:
          fg: white
      - name: event
        display:
          fg: blue
  - name: DBTrace
    matcher:
      event: DBTrace
    scheme:
      - name: ts
        postfix: " "
        display:
          fg: white
      - name: query
        display:
          fg: magenta
      - name: args
        optional: true
        prefix: " ["
        postfix: "]"
      - name: took
        display:
          fg: white
          bold: true
        prefix: " "
      - name: error
        optional: true
        prefix: " "
