# shared/reusable types.
# To use a shared type it must be referencd `as: <name>`
#  so with the example type it would be `as: severity`
types:
  - name: severity
    type: enum
    variants:
      - name: DBG
        display:
          fg: orange
          bold: true

# type of events and scheme of their rendering
events:
  - name: ReqLog
    matcher:
      event: RequestLog
    scheme:
      - name: severity
        prefix: "["
        postfix: "] "
      - name: ts
        display:
          fg: white
      - name: status
        display:
          fg: green
        prefix: " "
      - name: method
        prefix: " "
      - name: path
        prefix: " "
      - name: took
        display:
          bold: true
        prefix: " "
      - name: location
        optional: true
        prefix: " to: "
      - name: event
        skip: true
      - name: msg
        skip: true
      - name: traceId
        skip: true
      # - name: ts
      #   type: datetime
      # - special: rest
  - name: ServerStart
    matcher:
      event: ServerStart
    scheme:
      - name: severity
        prefix: "["
        postfix: "] "
      - name: ts
        postfix: " "
      - name: ip
        display:
          fg: green
      - literal: ":"
        display:
          fg: green
      - name: port
        display:
          fg: green
      - name: msg
        skip: true
      - name: event
        prefix:
          literal: " ("
          display:
            fg: white
        postfix:
          literal: ")"
          display:
            fg: white
        display:
          fg: blue
  - name: ServerShutdown
    matcher:
      event: ServerShutdown
    scheme:
      - name: severity
        prefix: "["
        postfix: "] "
      - name: ts
      - name: msg
        prefix: " "
      - name: event
        prefix:
          literal: " ("
          display:
            fg: white
        postfix:
          literal: ")"
          display:
            fg: white
        display:
          fg: blue

  - name: ServerStop
    matcher:
      event: ServerStop
    scheme:
      - name: severity
        prefix: "["
        postfix: "] "
      - name: ts
        postfix: " "
      - name: event
        prefix:
          literal: " ("
          display:
            fg: white
        postfix:
          literal: ")"
          display:
            fg: white
        display:
          fg: blue
      - name: msg
        skip: true
  - name: DBTrace
    matcher:
      event: DBTrace
    scheme:
      - name: severity
        prefix: "["
        postfix: "] "
      - name: ts
        postfix: " "
        display:
          fg: white
      - name: query
        display:
          fg: magenta
      - name: args
        optional: true
        prefix: " ["
        postfix: "]"
      - name: took
        display:
          fg: white
          bold: true
        prefix: " "
      - name: error
        optional: true
        prefix: " "
      - name: event
        skip: true
