# shared/reusable types.
# To use a shared type it must be referencd `as: <name>`
#  so with the example type it would be `as: severity`
types:
  - name: severity
    type: enum
    variants:
      - name: DBG
        display:
          fg: orange
          bold: true

# type of events and scheme of their rendering
events:
  - name: ReqLog
    matcher:
      event: RequestLog
    scheme:
      - name: asdf
      - literal: " "
      - name: ts
        display:
          fg: white
      - literal: " "
      - name: status
        display:
          fg: green
      - literal: " "
      - name: method
      - literal: " "
      - name: path
      - literal: " "
      - name: took
        display:
          bold: true
      # - name: ts
      #   type: datetime
      # - name: severity
      #   as: severity
      # - name: path
      # - special: rest
  - name: ServerShutdown
    matcher:
      event: ServerShutdown
    scheme:
      - name: ts
      - literal: " "
      - name: msg
  - name: ServerStop
    matcher:
      event: ServerStop
    scheme:
      - name: ts
      - literal: " "
      - name: event
  - name: DBTrace
    matcher:
      event: DBTrace
    scheme:
      - name: ts
      - literal: " "
      - name: query
        display:
          fg: magenta
      - literal: " ["
      - name: args
      - literal: "] "
      - name: took
      - literal: " "
      - name: error
