# shared/reusable types.
# To use a shared type it must be referencd `as: <name>`
#  so with the example type it would be `as: severity`
types:
  - name: timestamp
    type: time
    fg: hi-black
  - name: severity
    variants: []
    prefix: "["
    postfix: "]"

# type of events and scheme of their rendering
events:
  - name: ReqLog
    matcher:
      event: RequestLog
    scheme:
      - { name: severity, as: severity }
      - { name: ts, as: timestamp }
      - literal: " "
      - name: status
        variants:
          - { min: 200, max: 299, fg: green }
          - { min: 400, max: 499, fg: yellow, bold: true }
      - literal: " "
      - name: method
        variants:
          - { value: GET, fg: white, bold: true }
          - { value: POST, fg: blue }
          - { value: PUT, fg: yellow }
      - literal: " "
      - name: path
      - name: took
        type: duration
        bold: true
        prefix: " "
      - name: location
        optional: true
        prefix: " to: "
      - name: event
        skip: true
      - name: msg
        skip: true
      - name: traceId
        skip: true
      # - name: ts
      #   type: datetime
      # - special: rest
  - name: ServerStart
    matcher:
      event: ServerStart
    scheme:
      - name: severity
        as: severity
        postfix: " "
      - name: ts
        as: timestamp
        postfix: " "
      - name: ip
        fg: green
      - literal: ":"
        fg: green
      - name: port
        fg: green
      - name: msg
        skip: true
      - name: event
        fg: blue
        prefix:
          literal: " ("
          fg: white
        postfix:
          literal: ")"
          fg: white
  - name: ServerShutdown
    matcher:
      event: ServerShutdown
    scheme:
      - name: severity
        as: severity
        postfix: " "
      - name: ts
        as: timestamp
      - name: msg
        prefix: " "
      - name: event
        fg: blue
        prefix:
          literal: " ("
          fg: white
        postfix:
          literal: ")"
          fg: white

  - name: ServerStop
    matcher:
      event: ServerStop
    scheme:
      - name: severity
        as: severity
        postfix: " "
      - name: ts
        as: timestamp
        postfix: " "
      - name: event
        fg: blue
        prefix:
          literal: " ("
          fg: white
        postfix:
          literal: ")"
          fg: white
      - name: msg
        skip: true
  - name: DBTrace
    matcher:
      event: DBTrace
    scheme:
      - name: severity
        as: severity
        postfix: " "
      - name: ts
        as: timestamp
        postfix: " "
      - name: query
        fg: magenta
      - name: args
        optional: true
        prefix: " ["
        postfix: "]"
      - name: took
        fg: white
        bold: true
        prefix: " "
      - name: error
        optional: true
        prefix: " "
      - name: event
        skip: true

  - name: Rest
    matcher:
      msg:
        filled: true
    scheme:
      - name: severity
        as: severity
        postfix: " "
      - name: ts
        as: timestamp
        postfix: " "
      - name: msg
