- name: ts
  type: datetime
  src_format: 2006-01-02 15:04:05
  dst_format: 15:04
  fg: hi-white

- literal: " "

- name: severity
  fg: red
  bold: true
  prefix:
    literal: " "
    inherit: true
  postfix:
    literal: "+"
  enum:
  - value: DBG
    fg: red
    italic: true
  - value: TRC
    fg: cyan
  - value: INF
    fg: hi-blue
    strikethrough: true
  - value: WRN
    fg: yellow
  - value: ERR
    bold: true
    fg: hi-red
  - value: CRT
    fg: black
    bg: magenta
    bold: true
  - value: PNC
    bg: red
    fg: magenta

- literal: " "

- name: method
  fg: black
  bg: hi-blue
  bold: true
  prefix:
    literal: " "
    inherit: true
  postfix:
    literal: " "
    inherit: true

- literal: " "

- name: uri

- literal: " "

- name: dyn_array
  type: array
  optional: true

- literal: " "

- name: parameters
  type: object
